### PR TITLE
Meisha

### PR DESCRIPTION
**Pull request by mam288**
Added title and status to the models. It seems to be flagging the whole prefix as different.It looks like it's because there are two tabs instead of one. Does the number of tabs make a difference?

### CODE REVIEW

**Comment by balhoff** [comment]
@mam288 you will need to update your local repository from the `main` branch here first, otherwise the conflicts will prevent merging. Also, keep the filenames as they are here, e.g., `AOP_112.ttl`.

It seems like you're defining the `:` prefix twice. I would just not define it at all, since I don't think you are using it in the content. The tabs don't matter.

**Review by balhoff — CHANGES_REQUESTED** [review]
@mam288 you will need to update your local repository from the `main` branch here first, otherwise the conflicts will prevent merging. Also, keep the filenames as they are here, e.g., `AOP_112.ttl`.

It seems like you're defining the `:` prefix twice. I would just not define it at all, since I don't think you are using it in the content. The tabs don't matter.

**Comment by mam288** [comment]
@balhoff I pulled the main branch into my local repository so they should be the same now. I'm not sure what you mean by defining prefix twice? There are two @prefix : lines but they have different urls? Do I get rid of one?

**Comment by balhoff** [comment]
> @balhoff I pulled the main branch into my local repository so they should be the same now. I'm not sure what you mean by defining prefix twice? There are two @Prefix : lines but they have different urls? Do I get rid of one?

Yes, the second will just override the first. But there is no point to defining a `:` prefix if you aren't using it anywhere.

**Comment by mam288** [comment]
@balhoff Does it matter which one I remove?

**Comment by balhoff** [comment]
> @balhoff Does it matter which one I remove?

Sorry, I was mistaken, you are using the `:` prefix in the data: https://github.com/ExposuresProvider/noctua-models/blob/152e37cb4bd7723a976bddd2b81c80c7308699af/models/aop_100_model.ttl#L125 

So yes it does matter, since you need the IRIs to match any place where you have used the full IRI. An example is `<http://www.co-ode.org/ontologies/ont.owl#prostaglandin%20F2alpha>` and `:prostaglandin%20F2alpha` here: https://github.com/ExposuresProvider/noctua-models/blob/152e37cb4bd7723a976bddd2b81c80c7308699af/models/aop_100_model.ttl#L85-L92

So that tells you which `:` prefix you need to retain.

**Comment by mam288** [comment]
@balhoff In in this example I'd remove the first instance of @prefix? The code below individuals uses http://www.co-ode.org/ontologies/ont.owl) not http://www.semanticweb.org?

**Comment by balhoff** [comment]
> @balhoff In in this example I'd remove the first instance of @Prefix? The code below individuals uses http://www.co-ode.org/ontologies/ont.owl) not http://www.semanticweb.org?

Yes.

**Review by balhoff — APPROVED** [review]
Looks good!

**Pull request merged**
